spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://192.168.254.130:3306/universe'
    username: root
    password: 123456
  # session 失效时间 一天
  session:
    timeout: 86400